### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by 719media** [justintaddei/v-shared-element#1]
This library seems really cool. Is there an actual example source code of the page https://justintaddei.github.io/v-shared-element/ somewhere? It's unclear from the README on how exactly to use this library.
Thanks!

**Comment by justintaddei** [comment]
Thank you for the feedback.

Yes, the source is available on the [`example` branch](https://github.com/justintaddei/v-shared-element/tree/example). I'll make mention of the branch in the README so it's easier to discover for others.

If you'll let me know what else you found confusing, I'll try to improve the docs.

**Comment by 719media** [comment]
Once you sent me that branch, I could more easily figure the rest out, thanks.

Only issue I'm running into is that using `<keep-alive>` makes the transition only run once, and then never again for that namespace.

There are a lot of reasons people may use `<keep-alive>`, but mine is because the "parent component" uses infinite scrolling and additional content is loaded through ajax... so I want the user to be able to return to where they were without reloading the component from scratch.

**Comment by justintaddei** [comment]
The flicker is something I can probably fix because the element is copied (see the [illusory demo](https://justintaddei.github.io/illusory/) for an example) before the transition takes place. I'll be looking into this a lot more very soon.

`<keep-alive>` isn't something thought would cause problems I see now it very much does. I'll definitely be addressing this if it's possible. If you wouldn't mind creating a new issue for that specifically, I'll do my best to resolve it.

**Comment by 719media** [comment]
#2 created for keep-alive

**Comment by justintaddei** [comment]
Thank you. If you encounter any more issues don't hesitate to reach out!

**Comment by justintaddei** [comment]
I fixed the flickering on the example page. Turns out it was a 404 error caused because I wasn't respecting the base route. (In other words it wasn't an issue with the plugin. See commit #6fb1594 for the relevant changes)

Are you seeing the flickering you mentioned in your project as well?
